"""nine ops modules plus engineering enrichment

Revision ID: 10f7c5e73f7a
Revises: 53d3c88299a8
Create Date: 2026-09-15 19:20:04.828362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10f7c5e73f7a'
down_revision = '53d3c88299a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please ad! ###
    op.create_table('daily_reports',
    sa.Column('weather', sa.String(length=20), nullable=False),
    sa.Column('temp_c', sa.Float(), nullable=True),
    sa.Column('work_hours', sa.Float(), nullable=False),
    sa.Column('engineers_count', sa.Integer(), nullable=False),
    sa.Column('technicians_count', sa.Integer(), nullable=False),
    sa.Column('labor_count', sa.Integer(), nullable=False),
    sa.Column('equipment', sa.Text(), nullable=True),
    sa.Column('works_executed', sa.Text(), nullable=False),
    sa.Column('deliveries', sa.Text(), nullable=True),
    sa.Column('visitors', sa.Text(), nullable=True),
    sa.Column('delays', sa.Text(), nullable=True),
    sa.Column('safety_notes', sa.Text(), nullable=True),
    sa.Column('day_progress_pct', sa.Float(), nullable=False),
    sa.Column('next_plan', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('serial', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('root_id', sa.Integer(), nullable=True),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('signatory_name', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_reports_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_reports_report_date'), ['report_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_reports_root_id'), ['root_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_reports_serial'), ['serial'], unique=True)
        batch_op.create_index(batch_op.f('ix_daily_reports_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_reports_supersedes_id'), ['supersedes_id'], unique=False)
        batch_op.create_index('ix_drep_project_date', ['project_id', 'report_date'], unique=False)
        batch_op.create_index('ix_drep_project_status', ['project_id', 'status'], unique=False)

    op.create_table('safety_reports',
    sa.Column('area', sa.String(length=200), nullable=False),
    sa.Column('inspection_type', sa.String(length=20), nullable=False),
    sa.Column('hazard', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('responsible', sa.String(length=20), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('closure_date', sa.Date(), nullable=True),
    sa.Column('incidents_count', sa.Integer(), nullable=False),
    sa.Column('lost_time_injuries', sa.Integer(), nullable=False),
    sa.Column('toolbox_talks', sa.Integer(), nullable=False),
    sa.Column('ppe_compliance', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('serial', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('root_id', sa.Integer(), nullable=True),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('signatory_name', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('safety_reports', schema=None) as batch_op:
        batch_op.create_index('ix_hrep_project_date', ['project_id', 'report_date'], unique=False)
        batch_op.create_index('ix_hrep_project_status', ['project_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_safety_reports_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_safety_reports_report_date'), ['report_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_safety_reports_root_id'), ['root_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_safety_reports_serial'), ['serial'], unique=True)
        batch_op.create_index(batch_op.f('ix_safety_reports_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_safety_reports_supersedes_id'), ['supersedes_id'], unique=False)

    op.create_table('variation_orders',
    sa.Column('vo_no', sa.String(length=80), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('boq_ref', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('cost_impact', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('time_impact_days', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.String(length=20), nullable=False),
    sa.Column('attachments', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('serial', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('root_id', sa.Integer(), nullable=True),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('signatory_name', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('variation_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_variation_orders_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_variation_orders_report_date'), ['report_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_variation_orders_root_id'), ['root_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_variation_orders_serial'), ['serial'], unique=True)
        batch_op.create_index(batch_op.f('ix_variation_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_variation_orders_supersedes_id'), ['supersedes_id'], unique=False)
        batch_op.create_index('ix_vord_project_date', ['project_id', 'report_date'], unique=False)
        batch_op.create_index('ix_vord_project_status', ['project_id', 'status'], unique=False)

    with op.batch_alter_table('cost_variances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=False, server_default='ILS'))
        batch_op.add_column(sa.Column('vo_ref', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('schedule_impact_days', sa.Float(), nullable=False, server_default='0'))

    with op.batch_alter_table('material_submittals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin_country', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('certificates', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('test_report_ref', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('consultant_action', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('resubmit_due', sa.Date(), nullable=True))

    with op.batch_alter_table('progress_billings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('boq_ref', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('measurement_ref', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('progress_pct', sa.Float(), nullable=False, server_default='0'))

    with op.batch_alter_table('rfis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spec_ref', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('cost_impact', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('delay_days', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('response_action', sa.String(length=120), nullable=True))

    with op.batch_alter_table('site_inspections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('element', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('axes', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('concrete_class', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('slump', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cube_ids', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('pour_permit_ref', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('witness', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('standard_code', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('follow_up', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('attachments', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('subcontractor_performances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delay_days', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('penalty', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('incidents', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('recommendation', sa.String(length=20), nullable=False, server_default='استمرار'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please ad! ###
    with op.batch_alter_table('subcontractor_performances', schema=None) as batch_op:
        batch_op.drop_column('recommendation')
        batch_op.drop_column('incidents')
        batch_op.drop_column('penalty')
        batch_op.drop_column('delay_days')

    with op.batch_alter_table('site_inspections', schema=None) as batch_op:
        batch_op.drop_column('attachments')
        batch_op.drop_column('follow_up')
        batch_op.drop_column('standard_code')
        batch_op.drop_column('witness')
        batch_op.drop_column('pour_permit_ref')
        batch_op.drop_column('cube_ids')
        batch_op.drop_column('slump')
        batch_op.drop_column('concrete_class')
        batch_op.drop_column('axes')
        batch_op.drop_column('element')

    with op.batch_alter_table('rfis', schema=None) as batch_op:
        batch_op.drop_column('response_action')
        batch_op.drop_column('delay_days')
        batch_op.drop_column('cost_impact')
        batch_op.drop_column('spec_ref')

    with op.batch_alter_table('progress_billings', schema=None) as batch_op:
        batch_op.drop_column('progress_pct')
        batch_op.drop_column('measurement_ref')
        batch_op.drop_column('boq_ref')

    with op.batch_alter_table('material_submittals', schema=None) as batch_op:
        batch_op.drop_column('resubmit_due')
        batch_op.drop_column('consultant_action')
        batch_op.drop_column('test_report_ref')
        batch_op.drop_column('certificates')
        batch_op.drop_column('origin_country')

    with op.batch_alter_table('cost_variances', schema=None) as batch_op:
        batch_op.drop_column('schedule_impact_days')
        batch_op.drop_column('vo_ref')
        batch_op.drop_column('currency')

    with op.batch_alter_table('variation_orders', schema=None) as batch_op:
        batch_op.drop_index('ix_vord_project_status')
        batch_op.drop_index('ix_vord_project_date')
        batch_op.drop_index(batch_op.f('ix_variation_orders_supersedes_id'))
        batch_op.drop_index(batch_op.f('ix_variation_orders_status'))
        batch_op.drop_index(batch_op.f('ix_variation_orders_serial'))
        batch_op.drop_index(batch_op.f('ix_variation_orders_root_id'))
        batch_op.drop_index(batch_op.f('ix_variation_orders_report_date'))
        batch_op.drop_index(batch_op.f('ix_variation_orders_project_id'))

    op.drop_table('variation_orders')
    with op.batch_alter_table('safety_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safety_reports_supersedes_id'))
        batch_op.drop_index(batch_op.f('ix_safety_reports_status'))
        batch_op.drop_index(batch_op.f('ix_safety_reports_serial'))
        batch_op.drop_index(batch_op.f('ix_safety_reports_root_id'))
        batch_op.drop_index(batch_op.f('ix_safety_reports_report_date'))
        batch_op.drop_index(batch_op.f('ix_safety_reports_project_id'))
        batch_op.drop_index('ix_hrep_project_status')
        batch_op.drop_index('ix_hrep_project_date')

    op.drop_table('safety_reports')
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.drop_index('ix_drep_project_status')
        batch_op.drop_index('ix_drep_project_date')
        batch_op.drop_index(batch_op.f('ix_daily_reports_supersedes_id'))
        batch_op.drop_index(batch_op.f('ix_daily_reports_status'))
        batch_op.drop_index(batch_op.f('ix_daily_reports_serial'))
        batch_op.drop_index(batch_op.f('ix_daily_reports_root_id'))
        batch_op.drop_index(batch_op.f('ix_daily_reports_report_date'))
        batch_op.drop_index(batch_op.f('ix_daily_reports_project_id'))

    op.drop_table('daily_reports')
    # ### end Alembic commands ###
