"""versioning workflow plus dynamic field rules

Revision ID: 53d3c88299a8
Revises: ed9ec77b7fc2
Create Date: 2026-09-14 23:25:10.334259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53d3c88299a8'
down_revision = 'ed9ec77b7fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please ad! ###
    with op.batch_alter_table('cost_variances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('root_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('supersedes_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cost_variances_root_id'), ['root_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_variances_supersedes_id'), ['supersedes_id'], unique=False)

    with op.batch_alter_table('dynamic_fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rules', sa.JSON(), nullable=True))

    with op.batch_alter_table('material_submittals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('root_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('supersedes_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_material_submittals_root_id'), ['root_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_submittals_supersedes_id'), ['supersedes_id'], unique=False)

    with op.batch_alter_table('progress_billings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('root_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('supersedes_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_progress_billings_root_id'), ['root_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_billings_supersedes_id'), ['supersedes_id'], unique=False)

    with op.batch_alter_table('rfis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('root_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('supersedes_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_rfis_root_id'), ['root_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rfis_supersedes_id'), ['supersedes_id'], unique=False)

    with op.batch_alter_table('site_inspections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('root_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('supersedes_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_site_inspections_root_id'), ['root_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_inspections_supersedes_id'), ['supersedes_id'], unique=False)

    with op.batch_alter_table('subcontractor_performances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('root_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('supersedes_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_subcontractor_performances_root_id'), ['root_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subcontractor_performances_supersedes_id'), ['supersedes_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please ad! ###
    with op.batch_alter_table('subcontractor_performances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subcontractor_performances_supersedes_id'))
        batch_op.drop_index(batch_op.f('ix_subcontractor_performances_root_id'))
        batch_op.drop_column('supersedes_id')
        batch_op.drop_column('root_id')
        batch_op.drop_column('version')

    with op.batch_alter_table('site_inspections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_inspections_supersedes_id'))
        batch_op.drop_index(batch_op.f('ix_site_inspections_root_id'))
        batch_op.drop_column('supersedes_id')
        batch_op.drop_column('root_id')
        batch_op.drop_column('version')

    with op.batch_alter_table('rfis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rfis_supersedes_id'))
        batch_op.drop_index(batch_op.f('ix_rfis_root_id'))
        batch_op.drop_column('supersedes_id')
        batch_op.drop_column('root_id')
        batch_op.drop_column('version')

    with op.batch_alter_table('progress_billings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progress_billings_supersedes_id'))
        batch_op.drop_index(batch_op.f('ix_progress_billings_root_id'))
        batch_op.drop_column('supersedes_id')
        batch_op.drop_column('root_id')
        batch_op.drop_column('version')

    with op.batch_alter_table('material_submittals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_submittals_supersedes_id'))
        batch_op.drop_index(batch_op.f('ix_material_submittals_root_id'))
        batch_op.drop_column('supersedes_id')
        batch_op.drop_column('root_id')
        batch_op.drop_column('version')

    with op.batch_alter_table('dynamic_fields', schema=None) as batch_op:
        batch_op.drop_column('rules')

    with op.batch_alter_table('cost_variances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_variances_supersedes_id'))
        batch_op.drop_index(batch_op.f('ix_cost_variances_root_id'))
        batch_op.drop_column('supersedes_id')
        batch_op.drop_column('root_id')
        batch_op.drop_column('version')

    # ### end Alembic commands ###
