"""dynamic table line-item columns

Revision ID: 928273e63d76
Revises: 10f7c5e73f7a
Create Date: 2026-09-15 20:00:55.124693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928273e63d76'
down_revision = '10f7c5e73f7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please ad! ###
    with op.batch_alter_table('dynamic_fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_fields', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please ad! ###
    with op.batch_alter_table('dynamic_fields', schema=None) as batch_op:
        batch_op.drop_column('sub_fields')

    # ### end Alembic commands ###
