"""azadexa baseline plus ops modules

Revision ID: ed9ec77b7fc2
Revises: 
Create Date: 2026-09-14 23:11:34.253320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed9ec77b7fc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please ad! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('contractor', sa.String(length=200), nullable=True),
    sa.Column('client', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('company', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('cost_variances',
    sa.Column('boq_item', sa.String(length=250), nullable=False),
    sa.Column('boq_ref', sa.String(length=80), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('budgeted_qty', sa.Float(), nullable=False),
    sa.Column('budgeted_rate', sa.Float(), nullable=False),
    sa.Column('actual_qty', sa.Float(), nullable=False),
    sa.Column('actual_rate', sa.Float(), nullable=False),
    sa.Column('reestimated_qty', sa.Float(), nullable=True),
    sa.Column('reestimated_rate', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('serial', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('signatory_name', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cost_variances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_variances_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_variances_report_date'), ['report_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_variances_serial'), ['serial'], unique=True)
        batch_op.create_index(batch_op.f('ix_cost_variances_status'), ['status'], unique=False)
        batch_op.create_index('ix_cvar_project_date', ['project_id', 'report_date'], unique=False)
        batch_op.create_index('ix_cvar_project_status', ['project_id', 'status'], unique=False)

    op.create_table('material_submittals',
    sa.Column('material_name', sa.String(length=200), nullable=False),
    sa.Column('spec_section', sa.String(length=120), nullable=True),
    sa.Column('submittal_no', sa.String(length=80), nullable=True),
    sa.Column('revision', sa.String(length=20), nullable=True),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('sample_location', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('serial', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('signatory_name', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_submittals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_submittals_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_submittals_report_date'), ['report_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_submittals_serial'), ['serial'], unique=True)
        batch_op.create_index(batch_op.f('ix_material_submittals_status'), ['status'], unique=False)
        batch_op.create_index('ix_msub_project_date', ['project_id', 'report_date'], unique=False)
        batch_op.create_index('ix_msub_project_status', ['project_id', 'status'], unique=False)

    op.create_table('progress_billings',
    sa.Column('cert_no', sa.String(length=80), nullable=True),
    sa.Column('period_from', sa.Date(), nullable=True),
    sa.Column('period_to', sa.Date(), nullable=True),
    sa.Column('work_item', sa.String(length=250), nullable=False),
    sa.Column('qty_completed', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('retention_pct', sa.Float(), nullable=False),
    sa.Column('previously_certified', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('serial', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('signatory_name', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('progress_billings', schema=None) as batch_op:
        batch_op.create_index('ix_pbil_project_date', ['project_id', 'report_date'], unique=False)
        batch_op.create_index('ix_pbil_project_status', ['project_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_billings_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_billings_report_date'), ['report_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_billings_serial'), ['serial'], unique=True)
        batch_op.create_index(batch_op.f('ix_progress_billings_status'), ['status'], unique=False)

    op.create_table('project_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('role_in_project', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', name='uq_member_user_project')
    )
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.create_index('ix_member_project', ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_members_user_id'), ['user_id'], unique=False)

    op.create_table('report_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=20), nullable=True),
    sa.Column('gradient', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_templates_key'), ['key'], unique=True)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('contractor', sa.String(length=200), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('signatory_name', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_name', 'report_type', 'report_date', name='uq_project_type_date')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_project_name'), ['project_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_report_date'), ['report_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_report_type'), ['report_type'], unique=False)
        batch_op.create_index('ix_reports_type_date', ['report_type', 'report_date'], unique=False)

    op.create_table('rfis',
    sa.Column('subject', sa.String(length=250), nullable=False),
    sa.Column('discipline', sa.String(length=80), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('drawing_ref', sa.String(length=200), nullable=True),
    sa.Column('ball_in_court', sa.String(length=20), nullable=True),
    sa.Column('reply_due', sa.Date(), nullable=True),
    sa.Column('date_replied', sa.Date(), nullable=True),
    sa.Column('reply_summary', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('serial', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('signatory_name', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rfis', schema=None) as batch_op:
        batch_op.create_index('ix_rfi_project_date', ['project_id', 'report_date'], unique=False)
        batch_op.create_index('ix_rfi_project_status', ['project_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_rfis_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rfis_report_date'), ['report_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_rfis_serial'), ['serial'], unique=True)
        batch_op.create_index(batch_op.f('ix_rfis_status'), ['status'], unique=False)

    op.create_table('site_inspections',
    sa.Column('test_category', sa.String(length=20), nullable=False),
    sa.Column('test_type', sa.String(length=200), nullable=False),
    sa.Column('location_detail', sa.String(length=200), nullable=True),
    sa.Column('spec_reference', sa.String(length=200), nullable=True),
    sa.Column('result_value', sa.Float(), nullable=True),
    sa.Column('result_unit', sa.String(length=40), nullable=True),
    sa.Column('acceptance_min', sa.Float(), nullable=True),
    sa.Column('acceptance_max', sa.Float(), nullable=True),
    sa.Column('lab_name', sa.String(length=200), nullable=True),
    sa.Column('verdict', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('serial', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('signatory_name', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site_inspections', schema=None) as batch_op:
        batch_op.create_index('ix_insp_project_date', ['project_id', 'report_date'], unique=False)
        batch_op.create_index('ix_insp_project_status', ['project_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_inspections_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_inspections_report_date'), ['report_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_inspections_serial'), ['serial'], unique=True)
        batch_op.create_index(batch_op.f('ix_site_inspections_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_inspections_test_category'), ['test_category'], unique=False)

    op.create_table('subcontractor_performances',
    sa.Column('subcontractor', sa.String(length=200), nullable=False),
    sa.Column('trade', sa.String(length=120), nullable=True),
    sa.Column('period', sa.String(length=80), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('schedule_score', sa.Float(), nullable=False),
    sa.Column('safety_score', sa.Float(), nullable=False),
    sa.Column('compliance_score', sa.Float(), nullable=False),
    sa.Column('recommended_payment', sa.Float(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('serial', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('signatory_name', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subcontractor_performances', schema=None) as batch_op:
        batch_op.create_index('ix_sper_project_date', ['project_id', 'report_date'], unique=False)
        batch_op.create_index('ix_sper_project_status', ['project_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_subcontractor_performances_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subcontractor_performances_report_date'), ['report_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_subcontractor_performances_serial'), ['serial'], unique=True)
        batch_op.create_index(batch_op.f('ix_subcontractor_performances_status'), ['status'], unique=False)

    op.create_table('dynamic_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=60), nullable=False),
    sa.Column('label_ar', sa.String(length=200), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('placeholder', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'field_key', name='uq_template_field_key')
    )
    with op.batch_alter_table('dynamic_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dynamic_fields_template_id'), ['template_id'], unique=False)

    op.create_table('report_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('contractor', sa.String(length=200), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('signatory_name', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'project_name', 'report_date', name='uq_sub_template_project_date')
    )
    with op.batch_alter_table('report_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_submissions_project_name'), ['project_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_submissions_report_date'), ['report_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_submissions_template_id'), ['template_id'], unique=False)
        batch_op.create_index('ix_sub_template_date', ['template_id', 'report_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please ad! ###
    with op.batch_alter_table('report_submissions', schema=None) as batch_op:
        batch_op.drop_index('ix_sub_template_date')
        batch_op.drop_index(batch_op.f('ix_report_submissions_template_id'))
        batch_op.drop_index(batch_op.f('ix_report_submissions_report_date'))
        batch_op.drop_index(batch_op.f('ix_report_submissions_project_name'))

    op.drop_table('report_submissions')
    with op.batch_alter_table('dynamic_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dynamic_fields_template_id'))

    op.drop_table('dynamic_fields')
    with op.batch_alter_table('subcontractor_performances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subcontractor_performances_status'))
        batch_op.drop_index(batch_op.f('ix_subcontractor_performances_serial'))
        batch_op.drop_index(batch_op.f('ix_subcontractor_performances_report_date'))
        batch_op.drop_index(batch_op.f('ix_subcontractor_performances_project_id'))
        batch_op.drop_index('ix_sper_project_status')
        batch_op.drop_index('ix_sper_project_date')

    op.drop_table('subcontractor_performances')
    with op.batch_alter_table('site_inspections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_inspections_test_category'))
        batch_op.drop_index(batch_op.f('ix_site_inspections_status'))
        batch_op.drop_index(batch_op.f('ix_site_inspections_serial'))
        batch_op.drop_index(batch_op.f('ix_site_inspections_report_date'))
        batch_op.drop_index(batch_op.f('ix_site_inspections_project_id'))
        batch_op.drop_index('ix_insp_project_status')
        batch_op.drop_index('ix_insp_project_date')

    op.drop_table('site_inspections')
    with op.batch_alter_table('rfis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rfis_status'))
        batch_op.drop_index(batch_op.f('ix_rfis_serial'))
        batch_op.drop_index(batch_op.f('ix_rfis_report_date'))
        batch_op.drop_index(batch_op.f('ix_rfis_project_id'))
        batch_op.drop_index('ix_rfi_project_status')
        batch_op.drop_index('ix_rfi_project_date')

    op.drop_table('rfis')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index('ix_reports_type_date')
        batch_op.drop_index(batch_op.f('ix_reports_report_type'))
        batch_op.drop_index(batch_op.f('ix_reports_report_date'))
        batch_op.drop_index(batch_op.f('ix_reports_project_name'))

    op.drop_table('reports')
    with op.batch_alter_table('report_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_templates_key'))

    op.drop_table('report_templates')
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_members_user_id'))
        batch_op.drop_index('ix_member_project')

    op.drop_table('project_members')
    with op.batch_alter_table('progress_billings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progress_billings_status'))
        batch_op.drop_index(batch_op.f('ix_progress_billings_serial'))
        batch_op.drop_index(batch_op.f('ix_progress_billings_report_date'))
        batch_op.drop_index(batch_op.f('ix_progress_billings_project_id'))
        batch_op.drop_index('ix_pbil_project_status')
        batch_op.drop_index('ix_pbil_project_date')

    op.drop_table('progress_billings')
    with op.batch_alter_table('material_submittals', schema=None) as batch_op:
        batch_op.drop_index('ix_msub_project_status')
        batch_op.drop_index('ix_msub_project_date')
        batch_op.drop_index(batch_op.f('ix_material_submittals_status'))
        batch_op.drop_index(batch_op.f('ix_material_submittals_serial'))
        batch_op.drop_index(batch_op.f('ix_material_submittals_report_date'))
        batch_op.drop_index(batch_op.f('ix_material_submittals_project_id'))

    op.drop_table('material_submittals')
    with op.batch_alter_table('cost_variances', schema=None) as batch_op:
        batch_op.drop_index('ix_cvar_project_status')
        batch_op.drop_index('ix_cvar_project_date')
        batch_op.drop_index(batch_op.f('ix_cost_variances_status'))
        batch_op.drop_index(batch_op.f('ix_cost_variances_serial'))
        batch_op.drop_index(batch_op.f('ix_cost_variances_report_date'))
        batch_op.drop_index(batch_op.f('ix_cost_variances_project_id'))

    op.drop_table('cost_variances')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_name'))

    op.drop_table('projects')
    # ### end Alembic commands ###
